#include "include_voxel/voxel_parameters.h"

VoxelModelParams::VoxelModelParams(
    std::filesystem::path source_path,
    std::filesystem::path model_path,
    std::filesystem::path exec_path,
    int sh_degree,
    std::string images,
    float resolution,
    bool white_background,
    std::string data_device,
    bool eval)
    : source_path_(source_path),
      model_path_(model_path),
      sh_degree_(sh_degree),
      images_(images),
      resolution_(resolution),
      white_background_(white_background),
      data_device_(data_device),
      eval_(eval)
 {
     if (source_path.is_absolute())
         source_path_ = source_path;
     else
         source_path_ = exec_path / source_path;
 
     if (model_path.is_absolute())
         model_path_ = model_path;
     else
         model_path_ = exec_path / model_path;
 }

VoxelPipelineParams::VoxelPipelineParams(bool convert_SHs)
     : convert_SHs_(convert_SHs)
{}

VoxelOptimizationParams::VoxelOptimizationParams(
    int iterations,
    float geo_lr,
    float sh0_lr,
    float shs_lr,
    float optim_beta1,
    float optim_beta2,
    float optim_eps,
    std::vector<int> lr_decay_ckpt,
    float lr_decay_mult,
    int adapt_from,
    int adapt_every,
    int prune_every,
    int subdivide_every,
    bool filter_near_voxels,
    bool prune_far_voxels,
    bool prune_near_voxels_geometric,
    bool final_special_prune_enable,
    int prune_from,
    int prune_until,
    float prune_thres_init,
    float prune_thres_final,
    float prune_thres_final_at_target,
    int subdivide_from,
    int subdivide_all_until,
    float subdivide_samp_thres,
    float subdivide_prop,
    int subdivide_max_num,
    float lambda_dssim,
    bool use_l1,
    bool use_huber,
    float huber_thres,
    float lambda_tv_density,
    int   tv_from,
    int   tv_until,
    float ss_aug_max,
    float lambda_R_concen,
    float lambda_dist,
    int   dist_from,
    float lambda_T_concen,
    float lambda_T_inside,
    float lambda_normal_dmean,
    int   n_dmean_from,
    int   n_dmean_end,
    int   n_dmean_ks,
    float n_dmean_tol_deg,
    float lambda_ssim,
    float lambda_sparse_depth,
    int   sparse_depth_until,
    bool  enable_da2_uncertainty,
    int   level_uncertainty_from,
    float power_level_uncertainty,
    float lambda_ascending,
    int   ascending_from,
    float lambda_rectify,
    int   rectifiy_from,
    float lambda_scaling_penalty,
    int   scaling_penalty_from,
    int   scaling_penalty_end,
    int   multi_view_weight_from_iter,
    int   multi_view_interval,
    float multi_view_anneal_scale,
    float multi_view_ncc_weight,
    float multi_view_geo_weight,
    int   multi_view_patch_size,
    int   multi_view_sample_num,
    float multi_view_pixel_noise_th,
    float voxel_dropout_min
)
    :   iterations_(iterations),
        geo_lr_(geo_lr),
        sh0_lr_(sh0_lr),
        shs_lr_(shs_lr),
        optim_beta1_(optim_beta1),
        optim_beta2_(optim_beta2),
        optim_eps_(optim_eps),
        lr_decay_ckpt_(lr_decay_ckpt),
        lr_decay_mult_(lr_decay_mult),
        adapt_from_(adapt_from),
        adapt_every_(adapt_every),
        prune_every_(prune_every),
        subdivide_every_(subdivide_every),
        filter_near_voxels_(filter_near_voxels),
        prune_far_voxels_(prune_far_voxels),
        prune_near_voxels_geometric_(prune_near_voxels_geometric),
        final_special_prune_enable_(final_special_prune_enable),
        prune_from_(prune_from),
        prune_until_(prune_until),
        prune_thres_init_(prune_thres_init),
        prune_thres_final_(prune_thres_final),
        prune_thres_final_at_target_(prune_thres_final_at_target),
        subdivide_from_(subdivide_from),
        subdivide_all_until_(subdivide_all_until),
        subdivide_samp_thres_(subdivide_samp_thres),
        subdivide_prop_(subdivide_prop),
        subdivide_max_num_(subdivide_max_num),
        lambda_dssim_(lambda_dssim),
        use_l1_(use_l1),
        use_huber_(use_huber),
        huber_thres_(huber_thres),
        lambda_tv_density_(lambda_tv_density),
        tv_from_(tv_from),
        tv_until_(tv_until),
        ss_aug_max_(ss_aug_max),
        lambda_R_concen_(lambda_R_concen),
        lambda_dist_(lambda_dist),
        dist_from_(dist_from),
        lambda_T_concen_(lambda_T_concen),
        lambda_T_inside_(lambda_T_inside),
        lambda_normal_dmean_(lambda_normal_dmean),
        n_dmean_from_(n_dmean_from),
        n_dmean_end_(n_dmean_end),
        n_dmean_ks_(n_dmean_ks),
        n_dmean_tol_deg_(n_dmean_tol_deg),
        lambda_ssim_(lambda_ssim),
        lambda_sparse_depth_(lambda_sparse_depth),
        sparse_depth_until_(sparse_depth_until),
        enable_da2_uncertainty_(enable_da2_uncertainty),
        level_uncertainty_from_(level_uncertainty_from),
        power_level_uncertainty_(power_level_uncertainty),
        lambda_ascending_(lambda_ascending),
        ascending_from_(ascending_from),
        lambda_rectify_(lambda_rectify),
        rectifiy_from_(rectifiy_from),
        lambda_scaling_penalty_(lambda_scaling_penalty),
        scaling_penalty_from_(scaling_penalty_from),
        scaling_penalty_end_(scaling_penalty_end),
        multi_view_weight_from_iter_(multi_view_weight_from_iter),
        multi_view_interval_(multi_view_interval),
        multi_view_anneal_scale_(multi_view_anneal_scale),
        multi_view_ncc_weight_(multi_view_ncc_weight),
        multi_view_geo_weight_(multi_view_geo_weight),
        multi_view_patch_size_(multi_view_patch_size),
        multi_view_sample_num_(multi_view_sample_num),
        multi_view_pixel_noise_th_(multi_view_pixel_noise_th),
        voxel_dropout_min_(voxel_dropout_min)
{}
